### ISSUE TITLE
wp_date roadmap

### ISSUE THREAD

**Issue by Rarst** [Rarst/wp-date#1]
Welcome to `wp_date`! 

This is the initiative to fix up and improve Date/Time component of WordPress core.

This issue will be a living document of challenges, goals, and work in progress.

## Current situation

Date/Time core component was developed in PHP 4 language. It predates much of upstream PHP `DateTime` functionality. It was also written to make exclusive use of WP’s own localization functionality for the output.

At a certain point it went through a partial PHP 5 retrofit. It added a new timezone functionality, more reliant on PHP funcitonality. However the old custom timezone implementation is still in active use.

**In current state the component has a lot of major bugs and interoperability issues with PHP.**

## Challenges

The outstanding problems with the component fall into three categories.

### Code and documentation bugs

Due to the age and complexity of the component there a lot of **issues with incorrect operation of code**. On top of that the subtle and layered mechanics of it in many case come with **incorrect documentation**.

This type of issues needs direct fixes.

### Implementation design issues

The component has many **custom design decisions**. That leads to complication in use and unreliable operation.

The most prominent examples are:
- storage of local time without timezone information
- custom timezone math in old implementation
- use of custom timestamps, incompatible with general convention

Design issues are unfixable. Any functional change to adjust behavior would break backwards compatibility and downstream code.

This type of issues needs to removed from the code base (if possible) or deprecated.

### User experience issues

**Internal implementation and external API complexity** make the component a challenge to use.

Many operations lead to incorrect output of time information for humans and machines. This has negative implications in many areas:
- end–user experience
- programming interoperability
- communication over REST API
- SEO
-  and so on.

## Goals

The project aims to **improve the Date/Time component for three major groups of users**:

1. **For site owners** — to remove the problems in normal site operations and use of WP extensions.
2. **For developers** — to improve quality of API. Make implementation more reliable and PHP development easier.
3. **For platform users** — to improve reliability. Fix time data storage, its access and operation. Communication with other systems on PHP and REST API levels.

## Risks

The main risks are **backwards compatibility** and **lack of access to modern PHP**.

One of the main challenges is older timezone implementation. It is both in active use and requires large amounts of custom implementation code.

It is unclear to which degree design challenges can be fixed. Initial stages of the project will increase clarity about the state of the component.

At the moment I (Rarst) volunteer my time to organize and develop the project. There is **a risk of stall if my availability changes**. I am looking for sponsors to be able to focus on the project and reduce this risk, but it will go ahead regardless.

## Channels

- this repository — for ongoing development work and broad planning
- [core trac](https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&status=reviewing&component=Date%2FTime&col=id&col=summary&col=status&col=type&col=milestone&col=changetime&order=changetime) — for individual issues and submitting completed patches
- [slack #core-datetime](https://wordpress.slack.com/messages/core-datetime) — for discussions and tracking what needs merges

## Actions

- [x] audit [active core trac tickets](https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&status=reviewing&component=Date%2FTime&col=id&col=summary&col=status&col=type&col=milestone&col=changetime&order=changetime)
- [x] merge [available patches for known bugs](https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&status=reviewing&keywords=~has-patch&component=Date%2FTime&col=id&col=summary&col=status&col=type&col=milestone&col=changetime&order=changetime)
- [x] audit API functions and annotate known problems #3
- [x] [introduce unified timezone retrieval](https://core.trac.wordpress.org/ticket/24730) #4
- [x] implement new API functions #4
- [x] fix reliance on [default UTC time zone](https://core.trac.wordpress.org/ticket/44491)
- <del>[deprecate WP timestamps](https://core.trac.wordpress.org/ticket/44482)</del>
- <del>adjust time data storage and operation to canonical use of UTC #2 </del>

## References

- [Date/Time component](https://make.wordpress.org/core/components/date-time/)
- [DateTime crash course for WordPress developers](https://www.rarst.net/wordpress/datetime-crash-course/)
- [WpDateTime — DateTime extension for WordPress](https://github.com/Rarst/wpdatetime)
- [WordPress breaks time (and how to fix it)](https://wordpress.tv/2018/05/06/andrey-savchenko-wordpress-breaks-time-and-how-to-fix-it/) ([slides](https://www.rarst.net/slides/time/))
- [UTC is Enough for Everyone, Right?](https://zachholman.com/talk/utc-is-enough-for-everyone-right)

**Comment by heiglandreas** [comment]
Without wanting to be picky: I'd rather not "adjust time data storage and operations to canonical use of UTC".
I've written [a blogpost about why not to convert to UTC](https://andreas.heigl.org/2016/12/22/why-not-to-convert-a-datetime-to-timestamp/) and as far as I see it the possibilities for DateTimes in WordPress are given that they do not always only represent information within the next two weeks from "now". Therefore I'd rather keep the current approach of storing a DateTime and a Timezone. That's also what I usually suggest in my [Timezone-Talk](https://heiglandreas.github.io/slidedeck/time_is_an_illusion/20180609-dpc/index_online.html#/34)

Having said all that I'd happily contribute to bringing the best possible DateTime-handling class to WordPress!

**Comment by Rarst** [comment]
> Therefore I'd rather keep the current approach of storing a DateTime and a Timezone.

That is not what currently happens though. Currently what is stored by WordPress is a time **with unknown time zone**. Even if we add time zone separately it would be impractically complicated to use in SQL queries, which are currently broken for edge cases, unless ordering by GMT field is explicitly requested.

There would definitely be some discussion on this (feel free to open issue yourself!), but personally I don't see a way forward other than making UTC time canonical. What we have now is a _disaster_ and there are very few ways ahead due to backwards compatibility limitations.

**Comment by heiglandreas** [comment]
The timezone shouldn't be *unknown* as all DateTimes are created with the currently set default timezone and timestamps are always per definition UTC.

As the main Backend is MySQL it should be possible to implement a way to order dates using SQL like the following for sorting by UTC:

```sql
SELECT * FROM table ORDER BY CONVERT_TZ(myDateTime, myTimezone, 'UTC')
```
I'd definitely be interested in the edge cases!

Though timezone-handling will definitely be interesting on outdated systems. As soon as the timezone-database is not updated regularily on the PHP *and* on the MySQL-side all that effort is useless. There might be a way to handle timezones purely in PHP but that would still leave the MySQL-side…

But still I'd rather not recommend converting DateTimes to UTC/timestamps due to changes to the timezone-database between the conversion of the DateTime to UTC and the actual DateTime as those will result in wrong Informations being stored…

**Comment by Rarst** [comment]
New issue if you want to continue discussion please. :)

**Comment by Rarst** [comment]
If WP does indeed [bump minimum PHP version to 5.6](https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/) this spring that will **hugely** simplify a lot of issues in Date/Time.

**Comment by Rarst** [comment]
I had dropped canonical UTC from the roadmap, it doesn't seem appropriate for scheduling purposes and would be too major change to deal with at the moment.

**Comment by slaFFik** [comment]
So, WordPress did bump the min PHP version to 5.6.
Is the Actions list still relevant to this new information? Also, afaik, some date-related things were merged in WordPress 5.x.

**Comment by Rarst** [comment]
Yes, actions are quite relevant, I will be keeping them updated.

Some straight cleanup and fixes had shipped already (sans new PHP).

For 5.3 we have earmarked new unified `wp_timezone()` with PHP 5.6+ code, `date_i18n()` rewrite, and a looot of other fixes on top of that. Most of it is waiting for commit at the moment, I am not writing new patches before that portion settles in.

See [5.3 milestone](https://core.trac.wordpress.org/query?component=Date%2FTime&milestone=5.3&col=id&col=summary&col=milestone&col=type&col=status&col=changetime&order=changetime).

**Comment by Rarst** [comment]
Unified timezone retrieval ( `wp_timezone()` ) merged for WP 5.3

**Comment by Rarst** [comment]
All of planned new API #4 shipped for WP 5.3!

Shelving formally deprecating WP timestamps for now.

I think this will be about it for the project, I'll want to cover the changes and additions in a blog post at Make and then I am done.

**Comment by Rarst** [comment]
https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

And that's a wrap! ✔️
